# Generated by Django 3.2 on 2021-04-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='lead',
            field=models.TextField(default='Best little lead ever'),
            preserve_default=False,
        ),
    ]
