# Generated by Django 3.2 on 2021-04-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210420_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='logo',
        ),
    ]
