# Generated by Django 3.2 on 2021-04-23 04:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newsitem_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='lead',
            field=wagtail.core.fields.StreamField([('lead', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
    ]
