# Generated by Django 3.2.3 on 2021-05-14 03:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210513_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='author',
            field=wagtail.core.fields.StreamField([('author', wagtail.core.blocks.StructBlock([('first_name', wagtail.core.blocks.CharBlock(max_length=128)), ('surname', wagtail.core.blocks.CharBlock(max_length=256)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('biography', wagtail.core.blocks.RichTextBlock())])), ('button', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(max_length=64)), ('button_type', wagtail.core.blocks.ChoiceBlock(choices=[(('mdc-button', 'Text Only'), ('mdc-button--outlined', 'Outline'), ('mdc-button--raised', 'Solid Raised'))]))]))], blank=True),
        ),
    ]
