# Generated by Django 3.2.3 on 2021-05-14 03:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newsitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('blockquote', wagtail.core.blocks.BlockQuoteBlock()), ('svg', wagtailsvg.blocks.SvgChooserBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('button', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(max_length=64)), ('button_type', wagtail.core.blocks.ChoiceBlock(choices=[(('mdc-button', 'Text Only'), ('outlined', 'Outline'), ('raised', 'Solid Raised'))]))]))], blank=True),
        ),
    ]
