# Generated by Django 3.1.7 on 2021-02-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bloglistingpage_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingpage',
            name='svg',
        ),
    ]
