# Generated by Django 3.1.7 on 2021-04-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cta_btn_text',
            field=models.CharField(blank=True, default='Learn More', help_text='Call-To-Action Button Text', max_length=64),
        ),
    ]
